name: pedidos_online
version: 1.0.0+1
description: Aplicación móvil Flutter para gestión de pedidos online con PocketBase
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.5
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
